language: bash
services: docker

install:
  - git clone https://github.com/thyrlian/SonarOnDocker ~/workspace

script:
  - echo "=================================================="
  - docker-compose -v
  - echo "=================================================="
  # - docker-compose config
  - docker-compose up && docker ps --filter status=running
