sudo: required

language: bash

services:
  - docker

install:
  - git clone https://github.com/thyrlian/SonarOnDocker ~/SonarOnDocker

script:
  - docker-compose -f ~/SonarOnDocker/docker-compose.yml up
